module.exports = {
    MEDAL_FIRST_VIDEO_FEEDBACK: "MEDAL_FIRST_VIDEO_FEEDBACK",
    REGISTRY_NEW_CUSTOMER: "REGISTRY_NEW_CUSTOMER",
    UPDATE_MONTHLY_INVOICING: "UPDATE_MONTHLY_INVOICING",
    REGISTRY_NEW_CUSTOMER_TEST: "REGISTRY_NEW_CUSTOMER_TEST",
} 