module.exports = {
    MEDAL_3_REVENUES: "MEDAL_3_REVENUES",
    MEDAL_5_REVENUES: "MEDAL_5_REVENUES",
    MEDAL_10_REVENUES: "MEDAL_10_REVENUES",
    MEDAL_20_REVENUES: "MEDAL_20_REVENUES",
    MEDAL_30_REVENUES: "MEDAL_30_REVENUES",
    MEDAL_FIRST_PARTNER: "MEDAL_FIRST_PARTNER",
    MEDAL_FIRST_VIDEO_FEEDBACK: "MEDAL_FIRST_VIDEO_FEEDBACK",
} 