module.exports = {
    MEDAL_3_REVENUES: "MEDAL_3_REVENUES",
    MEDAL_5_REVENUES: "MEDAL_5_REVENUES",
    MEDAL_10_REVENUES: "MEDAL_10_REVENUES",
    MEDAL_20_REVENUES: "MEDAL_20_REVENUES",
    MEDAL_30_REVENUES: "MEDAL_30_REVENUES",
    FIRST_PARTNER: "FIRST_PARTNER",
    FIRST_CONTRACT: "FIRST_CONTRACT",
    VIDEO_FEEDBACK: "VIDEO_FEEDBACK",
} 